scss_files: "src/scss/**/*.scss"

severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: false

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true
    exclude:
      - "src/scss/mixins/ui/_buttons.scss"

  PrivateNamingConvention:
    enabled: true
    prefix: _
    exclude:
      - "src/scss/mixins/ui/_buttons.scss"

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes

  Comment:
      enabled: false

  PseudoElement:
      enabled: false

  UnnecessaryParentReference:
      enabled: false

  MergeableSelector:
      enabled: false

  SpaceBetweenParens:
      enabled: false
